import React from 'react'
import { Button, TextField } from '@material-ui/core';
import { URL_OTP_REGISTER } from '../helpers/constants';
import { getLoginFromJWT, setAuthToken } from '../helpers/auth';
import QRCode from "qrcode.react";
import axios from 'axios';

export default class OTPRegister extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      user: "",
      token: "",
      secret: "",
      qrcode: ""
    }
  }
  registerOTP = () => {
    axios.post(URL_OTP_REGISTER, {
      token: this.state.token,
      secret: this.state.secret,
    }).then(res => {
      if (res.status !== 200) {
        throw new Error("Couldn't save OTP token")
      } else {
        return res.data
      }
    }).then((res) => {
        console.log(res)
        if(res.data) {
            setAuthToken(res.data)
        }
    });
  }
  componentDidMount() {
    this.setState({user: getLoginFromJWT()})

    axios.get(URL_OTP_REGISTER).then(res => {
      if (res.status !== 200) {
        throw new Error("Couldn't load payloads")
      } else {
        return res.data
      }
    }).then((res) => {
      this.setState({ secret: res.data.secret})
    });
  }
  render() {
    return (
      <div>
        <div>
          <span>Register a new OTP for this account</span> <br/>
          <span className="hint">This is compatible with Google Authenticator or any other TOTP App, like Authy</span>
          <span> Instructions:</span>
          <ul>
            <li>Scan the QR Code with your 2FA App.</li>
            <li>Enter the code generated by your app in the OTP input</li>
            <li>Validate</li>
          </ul>
        </div>
        <div>
          <QRCode value={`otpauth://totp/${this.state.user}?secret=${this.state.secret}&issuer=WonderXSS`} />
        </div>
        <div>
          <TextField
            onChange={(event) => this.setState({ token: event.target.value })}
            helperText="(6 digits)"
            placeholder="OTP Token"
            />
          <Button onClick={this.registerOTP}>Validate</Button>
        </div>
      </div>
    )
  }
}